config/routes.rb
Codestalk::Application.routes.draw do

  resources :comments, except: [:index]
  resources :packages
  resources :projects
  resources :snippets
  resources :libraries

  get "projects/edit"
  get "projects/new"
  get "user/edit"
  get "user/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :snippet_id, :user_id, :user, :snippet
  belongs_to :user
  belongs_to :snippet
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :require_login!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # _index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html {
          redirect_to session[:return_to], notice: 'Comment was successfully created.'
          session[:return_to] = nil
        }

        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html {
          redirect_to session[:return_to], notice: 'Comment was successfully updated.'
          session[:return_to] = nil
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html {
        redirect_to session[:return_to]
        session[:return_to] = nil
      }
      format.json { head :no_content }
    end
  end

  private

  def require_login!
    unless user_signed_in?
      redirect_to login_path,
                  alert: "Bitte melden Sie sich zuerst an."
    end
  end
end

app/views/comments/_form.html.erb
<% @comment = Comment.new %>
<div class="modal-body">
  <%= form_for(@comment) do |f| %>
      <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <input type="hidden" name="comment[snippet_id]" value="<%= snippet %>">
      <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">

      <div class="field">
        <%= f.text_area :comment %>
      </div>
      </div>

      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <%= f.submit "Save changes", :class => "btn btn-primary" %>
      </div>

  <% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Snippet</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= comment.snippet_id %></td>
    <td><%= comment.user_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Snippet:</b>
  <%= @comment.snippet_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>