config/routes.rb
Codestalk::Application.routes.draw do

  resources :comments, except: [:index]
  resources :packages
  resources :projects
  resources :snippets
  resources :libraries

  get "projects/edit"
  get "projects/new"
  get "user/edit"
  get "user/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :title, :description, :user_id, :user
  belongs_to :user
  has_many :projects, dependent: :destroy
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  before_filter :require_login!

  def index
    @libraries = Library.all

    respond_to do |format|
      format.html # _index.html.erb
      format.json { render json: @packages }
    end
  end

  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @library }
    end
  end

  def edit
    @library = Library.find(params[:id])
  end

  def show
    @library = Library.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @library }
    end
  end

  def update
    @library = Library.find(params[:id])

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @library = Library.new(params[:library])
    @library.user_id = current_user

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render json: @library, status: :created, location: @library }
      else
        format.html { render action: "new" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end

  private

  def require_login!
    unless user_signed_in?
      redirect_to login_path,
                  alert: "Bitte melden Sie sich zuerst an."
    end
  end
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Listing libraries</h1>

<table>
  <tr>
    <th>Library</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libraries.each do |library| %>
  <tr>
    <td><%= library.title %></td>
    <td><%= library.description %></td>
    <td><%= library.user_id %></td>
    <td><%= link_to 'Show', library %></td>
    <td><%= link_to 'Edit', edit_library_path(library) %></td>
    <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @library.title %>
</p>

<p>
  <b>Description:</b>
  <%= @library.description %>
</p>


<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>