config/routes.rb
Codestalk::Application.routes.draw do

  resources :comments, except: [:index]
  resources :packages
  resources :projects
  resources :snippets
  resources :libraries

  get "projects/edit"
  get "projects/new"
  get "user/edit"
  get "user/show"
  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">codeStalk</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Snippets", snippets_url %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_noticebar.html.erb
<% if flash[:alert] %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <h4 class="alert-heading">Attention!</h4>
      <%= flash[:alert] %>
    </div>
<% end %>

<% if flash[:notice] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <%= flash[:notice] %>
    </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Navigation</li>
    <li>
      <div style='overflow:auto'>
        <% if user_signed_in? %>
            <i class="icon-user"></i><%= link_to current_user.name, user_show_path %><br>
            <i class="icon-off"></i><%= link_to 'Logout', logout_path %>
        <% else %>
            <a href="/auth/github">
              <i class="icon-lock"></i>
              Login
            </a>
        <% end %>
      </div>
    </li>

    <% if user_signed_in? %>
        <li class="nav-header">Create</li>
        <li>
          <div style='overflow:auto'>
            <i class="icon-book"></i><%=  link_to "New Library", new_library_path %><br>
            <i class="icon-bookmark"></i><%= link_to 'New Project', new_project_path %><br>
            <i class="icon-inbox"></i><%= link_to 'New Package', new_package_path %><br>
            <i class="icon-file"></i><%= link_to "New Snippet", new_snippet_path %>
          </div>
        </li>
    <% end %>

    <% if user_signed_in? %>
        <li class="nav-header">Snippets</li>
        <li>
          <% Library.all.each do |lib| %>
              <%= link_to lib.title, edit_library_path %>
              <ul>
                <% lib.projects.each do |project| %>
                    <li>
                      <%= link_to project.title, project %>
                      <ul>
                        <% project.packages.each do |package| %>
                            <li>
                              <%= link_to package.title, package %>
                            </li>
                        <% end %>
                      </ul>
                    </li>
                <% end %>
              </ul>
          <% end %>
        </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <title>codeStalk</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="codeStalk - Source Code Management System">
  <meta name="author" content="Konstantin Schuler">
  <%= stylesheet_link_tag "coderay", "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 for IE6-8 support of HTML5 elements -->
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
</head>

<body style="background:url(http://dl.dropbox.com/u/60731690/grids.gif)">

<%= render 'layouts/navbar' %>

<div class="container">
  <div class="row-fluid">

    <div class="span2">
      <%= render 'layouts/sidebar' %>
    </div>

    <div class="span10">

      <%= render 'layouts/noticebar' %>

      <div class="well">
        <div class="row-fluid">
            <%= yield %>
        </div>
      </div>
    </div>

  </div>

  <hr>
  <footer>
    <div class="container">
      <p>&copy; 2012</p>
    </div>
  </footer>
</div>

<script src="http://twitter.github.com/bootstrap/assets/js/jquery.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-transition.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-scrollspy.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-button.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-carousel.js"></script>
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js"></script>

</body>
</html>